### ISSUE TITLE
Handle failure to move recordings

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/devtools#6107]
We're adding controls to the backend to prevent moving recordings between storage locations. Right now, errors for this operation aren't handled gracefully by the frontend and will need to be.

**Comment by jaril** [comment]
> My suggestion would be to verify that we have the monitoring in place to know if people are hitting this so we know before users start yelling. It might be caught already by Sentry but I haven't verified.

Good call. Got any STRs?

**Comment by ryanjduffy** [comment]
https://sentry.io/organizations/replay/issues/2791294424

**Comment by jaril** [comment]
HA okay data is good. Turns out this isn't as rare (<10x/month) as I imagined it might be:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/15959269/169558527-bd4b6ade-5648-4298-81de-bcbabe31ab44.png">

Let me slide it into next week's sprint. Collaboration is deprioritized but this seems to be a pretty basic, core thing that we ought to figure out.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-139](https://linear.app/replay/issue/FE-139/handle-failure-to-move-recordings)
