### ISSUE TITLE
Toggling from DevTools to Viewer can default wrong

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6423]
Repro:

* Load a new Replay
* Replay Info is default in Viewer
* Go to DevTools
* Replay Sources is default in DevTools
* Go back to Viewer

Expected:

* Viewer should show DevTools

Actual:

* Viewer is showing Comments

**Comment by jaril** [comment]
> Repro:
> 
> * Load a new Replay
> * Replay Info is default in Viewer
> * Go to DevTools
> * Replay Sources is default in DevTools
> * Go back to Viewer
> 
> Expected:
> 
> * Viewer should show DevTools
> 
> Actual:
> 
> * Viewer is showing Comments

Not sure if this is clear — do you mean that the expected behavior should be that viewer should show replay info?

If you can attach a loom/replay that would be 👌.

**Comment by jasonLaster** [comment]
@jaril i believe this is saying that we should store a selected sidebar for the devtools and viewer. This way toggling modes doesn't blow away the saved state for the other.

**Comment by jonbell-lot23** [comment]
Whoops, I had a typo. Yes, it should show Replay Info

**Comment by bvaughn** [comment]
Observation: It feels like there are two different categories of "state" here:
* State that belongs to the Replay recording level (e.g. saved and pending comments, the current zoomed-in point on the timeline, etc.).
* State that belongs to the tab– Viewer or DevTools (e.g. which sub-section you've selected and drilled into).

I think the 2nd category of state is mostly applicable to DevTools since it's a superset of the panels available in the Viewer.

Also maybe worth pointing out that I think we need to move pending comments from Redux to Apollo soon. This will allow users to have multiple pending (unpublished) comments at once and will mean that you won't "lose" a draft comment in the sources panel (for example) just because you switched to the viewer and clicked around.

**Comment by jasonLaster** [comment]
@bvaughn for context we currently back some Redux state with `ReplaySession` in indexDB. This works pretty well for Redux, but not sure what the parallel if any would be for apollo. 
https://cs.github.com/RecordReplay/devtools/blob/4673a3e7a0dd24ccbcd7b37f539c5a72c8779641/src/ui/setup/prefs.ts#L137-L161

The only use case I see is saving draft comments when you're logging in... Important, but lets not go crazy for ...

**Comment by bvaughn** [comment]
@jasonLaster I think you're distinguishing between which types of state we _persist_ between sessions and which we don't? That seems like a separate (but also interesting) category to discuss.

I was only talking about which parts of the app "own" which kinds of state.

**Comment by jonbell-lot23** [comment]
Going through UI polish tasks and adding comments:

Hey @jaril can we roll forward on this? I think we're in agreement about the high level thing I filed (once I fixed my typo), and then these other conversations sound like other issues we can spin up.

**Comment by jaril** [comment]
> Going through UI polish tasks and adding comments:
> 
> Hey @jaril can we roll forward on this? I think we're in agreement about the high level thing I filed (once I fixed my typo), and then these other conversations sound like other issues we can spin up.

Yeah this is ready to go! 

@souporserious mind taking this on? Should be an easy win.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-149](https://linear.app/replay/issue/FE-149/toggling-from-devtools-to-viewer-can-default-wrong)
