### ISSUE TITLE
Clicking on breakpoint timeline does nothing

### ISSUE THREAD

**Issue by bhackett1024** [replayio/devtools#6548]
In this replay, there were a few times when I tried to click on the breakpoint timeline to jump to one of the hits, but nothing happened, and it doesn't look like we were waiting on any backend messages afterwards.

https://app.replay.io/recording/view-long-replay--1afe2dc1-646f-4403-941c-5f68c5e8e11a?point=139218459549484050787382377125518521&time=46900&hasFrames=true

**Comment by hbenl** [comment]
The breakpoint timeline click is handled correctly: you clicked on the logpoint that you were already paused at.
The real issue is that the UI didn't show any frames or scopes for the current (initial) pause. This happened because when we try to create the pause, that region hasn't been loaded yet, so the `Session.createPause` command fails, hence `Pause.createWaiter` is rejected and `Pause.getFrames()` fails when it tries to `await this.createWaiter` (and there's no UI yet showing that fetching the frames failed).
Has the handling of loaded regions in `Session.createPause` changed recently? Otherwise I'd be surprised that we haven't noticed this so far, it should happen quite often when you open a replay link that has a `point` parameter for a pause with frames.

**Comment by jcmorrow** [comment]
Got another good replay of this: https://app.replay.io/recording/cant-create-pause-on-start--74ce924b-abc3-44ac-b9ec-3c65b02b52f6

**Comment by jaril** [comment]
Bumped this to next week's sprint!

**Comment by jcmorrow** [comment]
Closed by https://github.com/replayio/devtools/pull/7009
