### ISSUE TITLE
Analysis based react devtools backend

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6565]
### Discussed in https://github.com/RecordReplay/devtools/discussions/6188

<div type='discussions-op-text'>

<sup>Originally posted by **bhackett1024** April  2, 2022</sup>
Currently we have a version of the react devtools backend which we load into every recording made using the replay browser.  Any react on the page will detect this backend and call into it, and it will add annotations to the recording which clients inspecting the recording can read and use to reconstruct the react state at any point in the recording.

This approach works but it doesn't scale well in a couple of ways:

1. The backend version is fixed for the lifetime of a recording, and a matching version of the frontend needs to be used in order to inspect its react state.  This makes it hard to upgrade the frontend / backend without breaking support for older recordings.
2. The backend is a substantial amount of code, and if we wanted to do something similar for other framework devtools we would potentially need to load quite a bit of code into every recording, on the off chance the backend would be needed.

It would be better if we didn't load a specific version of the backend into each recording.  There is already an interface between the devtools backend and the react code running on the page which works across different versions of react.  If the client loaded both the frontend and the backend for the react devtools (where the versions always match), and inspected the recording to find all the sites where react would have called into the backend, it should be able to extract the necessary information from those sites to populate its copy of the backend with the react state changes made throughout the recording.

We should be able to find the sites where react would have called into the backend by loading a shim version of the backend into each recording which is much smaller and just annotates the recording with all the calls that react is making.

The main unknowns for me is understanding what information the backend needs from these sites in order to work, and how difficult it would be to get this information from the recording instead of values that are being passed in.  I suspect the protocol is not expressive enough yet to deal with this use case.  Mainly, each site will be a different pause point, and we don't have a way to compare objects between different pauses.  So if the backend keeps track of metadata for a react object at one site, it won't be able to determine that object's metadata when it is accessed at a different site.  We've wanted to address this limitation for a while though, and being able to improve the architecture of our react devtools support and address the above difficulties would be a good impetus for this.</div>

**Comment by bhackett1024** [comment]
The above discussion has more background, but earlier today I started looking into how the react devtools backend works a little more to get a better understanding of what it is doing and how that maps onto both an analysis based backend and the different approaches for persistent object IDs being considered.

So, when the devtools backend gets a welcome message it looks for all renderers on the page and builds up the set of operations describing them from that initial state.  With the analysis based backend we can see the renderers when they're created so I think we can largely ignore the operations to set up their initial state.  (I think there is a race here between the initial react updates and the backend getting its welcome message, @hbenl might have encountered this before.)

Most of the operation data looks like it is encoding strings which appear in the react tree (getStringID) and changes to the tree (TREE_OPERATION_*).  These both seem to largely happen under handleCommitFiberRoot, where mountFiberRecursively and/or updateFiberRecursively are called to find all the tree changes and record them.  These functions don't seem to have to walk the entire tree each time a commit happens, and this is the part that I'm the least clear on.  It looks like there are some invariants indicating whether anything has changed since the last commit for a fiber or any of its children based on the child and alternate properties.

For the V0 persistent object ID implementation, when recording at each place where handleCommitFiberRoot would be called, we need to ensure that all the possibly-changed fibers which the backend could traverse and objects which they're compared to have persistent IDs so that these objects can be compared and getOrGenerateFiberID can be called for any of them.  This would be a similar traversal to what the backend is doing, though with (hopefully) less overhead.  With the V1 persistent object ID implementation this separate traversal and its complexity / overhead wouldn't be necessary.

Loading a facebook.com feed for one of our test accounts, I see 50 places where handleCommitFiberRoot was called, triggering 19623 calls to updateFiberRecursively and 3112 calls to recordMount (which I think is the main operation that gets recorded, though I'm not sure).

I think ultimately it will be a lot more efficient --- both in terms of speed and the data that needs to be sent to the client --- to run the backend within the processes replaying in the backend as part of an analysis and send the operations back to the client instead of information about all the fibers which need to be traversed in handleCommitFiberRoot.  We can't easily support that right now with how our analyses work, but running analysis JS within replaying processes was part of how these were originally envisioned to work and could be supported.  As an intermediate step we could run the entire backend including the traversal logic in the client, but that won't be a good long term solution.

**Comment by bhackett1024** [comment]
I just created an experimental PR for this which goes with a couple other PRs:

* https://github.com/RecordReplay/backend/pull/5312 has backend changes to support persistent object IDs.
* https://github.com/RecordReplay/gecko-dev/pull/844 adds support to compute persistent object IDs within gecko and adds annotations at places where react calls into the backend.

The goal here is to be able to detect the places where react commits fiber changes in a recording, and use the protocol to compute the operations which the react devtools backend in the recording separately computes.  We can check these are equal, and once we're ready to switch onto this we won't need the react devtools backend to run at all while recording.

The fiber commits can be found using the new annotations in https://github.com/RecordReplay/gecko-dev/pull/844.  From here we could perform an analysis at each of these points, but I think it's simpler for now to just do a big evaluation at each of these points, injecting code taken from the backend into the replaying process to compute the operations and encode them as an array like the backend does normally.

This follows along with the goal above to not send information about the individual objects back and do as much computation as we can within the replaying processes.  The main trick though is that when doing these evaluations we can't access state which the backend separately computed at other fiber commits.  This impacts the backend's mapping from react fibers to fiber IDs, which are numeric identifiers for fibers computed by the backend and used to refer to fibers in the returned operations.  Instead of computing these fiber IDs inside the evaluations, we'll need to use the persistent IDs for the fibers instead, which *are* state that is consistent between the different evaluations, and are the key thing needed in the protocol for this stuff to work at all.  It should be straightforward for the operations produced by the evaluations to use persistent IDs instead of fiber IDs, and for the client to create a mapping persistent ID => fiber ID which it can use to substitute these out and get identical operations to what the backend would have produced.

So far I haven't added any actual code from the backend, but we're able to find all the fiber commits in a simple react app, create pauses at all of them and do an evaluation returning the persistent ID for the roots at each of those commits.  These persistent IDs are all the same, indicating that the root fiber is the same for all of the commits.  That doesn't look like much, but it's a new capability we've never had before using the protocol and will open up this and a lot more possible functionality.

<img width="651" alt="Screen Shot 2022-05-06 at 2 18 40 PM" src="https://user-images.githubusercontent.com/1062578/167217839-8028962f-c2ef-4f28-9c2c-8a7cadafc75e.png">

**Comment by bhackett1024** [comment]
With the latest version of the PR, we're able to perform evaluations in the client that construct equivalent operations to what the embedded backend generated in a simple react app.  Here is a replay with a comment:

https://app.replay.io/recording/client-driven-backend--d6175557-c96c-433b-9327-e6eaf8d78102?point=31802818260780281134188576441892953&time=19168.845901639343&hasFrames=true

Here are the operations which the embedded backend generated:

```
[1,1,4,1,112,1,102,1,1,11,0,0,1,0,1,3,5,1,0,1,0,7,3,1,1,4,5,3,0,2,0]}
[1,1,4,1,100,1,49,1,6,5,4,0,1,2]}
[1,1,4,1,100,1,50,1,8,5,4,0,1,2,3,4,2,6,8]}
[1,1,0,2,1,6]
```

Here is what the evaluations produced:

```
[1,148,4,1,112,1,102,1,148,11,0,0,1,0,1,152,5,148,0,1,0,7,152,1,1,153,5,152,0,2,0]
[1,148,4,1,100,1,49,1,160,5,153,0,1,2]
[1,148,4,1,100,1,50,1,163,5,153,0,1,2,3,153,2,160,163]
[1,148,0,2,1,160]
```

These are equivalent except that the IDs which the evaluations use for fibers are different from the ones used by the embedded backend.  The embedded backend uses a fiberToIDMap which persists between fiber commits, while the evaluations use the persistent IDs computed for fibers.  Applying the substitution below to the evaluation-generated operations renders them identical to the embedded backend operations.

```
1 => 148
3 => 152
4 => 153
6 => 160
8 => 163
```

**Comment by bhackett1024** [comment]
The backend and gecko changes are in place now for computing persistent IDs for "new" objects like React fibers when using the "enablePersistentIDs" experimental setting, and annotations for places where calls are made into the react devtools from react itself are being added to recordings made with the latest browser.

This is as far as I can reasonably take things for now.  As a next step, someone can either:

1. Update the PR I created so that we only enable persistent IDs when a setting is on (we only want to do this conditionally as it will slow down replaying by an unknown amount and will disable snapshots in the backend), land it, and use it as a basis for further development.

2. Not land the PR but develop a new one based on what this is doing with backend evaluations and persistent IDs.

At some point we'll need to measure the overhead of tracking persistent IDs for these "new" objects, though I don't expect that to be much of an obstacle given how things are designed.  We'll also need to update the backend to always enable persistent IDs and support using snapshots with them.  Before doing that, I think we should do more work in the client to fill in the backend devtools implementation and integrate it with the react devtools tab, all behind the experimental setting.  This will make sure we have all the backend pieces we need, and also avoids needing to do more backend work to finalize things until we're ready to commit to this, since there's a lot of other frontend work going on right now.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-157](https://linear.app/replay/issue/FE-157/analysis-based-react-devtools-backend)
