### ISSUE TITLE
Stuck frame progress slider 

### ISSUE THREAD

**Issue by bhackett1024** [replayio/devtools#6768]
I've run into an intermittent problem using the frame slider in the devtools where it gets stuck on --- moving the mouse around without holding it down or clicking moves the frame slider around as if the mouse was down.  I haven't gotten a replay yet, it doesn't seem to be easily triggered (I should start recording all the time when viewing replays).

**Comment by bhackett1024** [comment]
https://user-images.githubusercontent.com/1062578/168432049-f36acfe8-5ccb-4b52-bed3-cd2b80c83017.mov

**Comment by markerikson** [comment]
Hmm. @bvaughn , is this maybe similar to the issues you saw with dragging the focus mode slider?

**Comment by bvaughn** [comment]
Haven't looked at this code but my guess is that we're probably not exiting drag-active state on mouse-leave or something.

**Comment by bvaughn** [comment]
> One additional thing I've noticed is that `document.removeEventListener` is actually a sentry-wrapped function, it's monkey-patched.

I have seen this in the past (recently, though I can't recall on which issue) and share his suspicion of Sentry.

**Comment by Andarist** [comment]
It's hardly any scientific proof but I have *very* good record in reproducing this in Chrome and after I've restored **both** of the `document.addEventListener` and `document.removeEventListener` (to get rid of Sentry from those two) I can no longer repro this.

**Comment by Andarist** [comment]
One additional piece of information... so what is set on `document.addEventListener` and `document.removeEventListener` are actually LogRocket wrappers... their implementation can be roughly seen here:
https://unpkg.com/browse/logrocket@2.2.1/dist/build.umd.js#L1045

There is a strong expectation here that a `func.__lr_wrapper__` is supposed to be removed (when it exists) and that property is created on the "original" function (the one actually passed as argument) within the overridden `addEventListener`. 

I've rechecked what is actually left attached to the document when the bug occurs (`getEventListeners(document).mousemove[0].listener`) and that is actually **not** the LogRocker function... it's some other wrapper from Sentry. It's implementation can be seen here:
https://github.com/getsentry/sentry-javascript/blob/c518955b774e5bbc36e7f1a22410703469911a2a/packages/browser/src/helpers.ts#L84

So... ye, the LogRocket's `removeEventListener` didn't have a chance to remove the **correct** listener since it's not the LogRocket's [`wrapped`](https://unpkg.com/browse/logrocket@2.2.1/dist/build.umd.js#L943) that is attached to the document nor it is the original function. 

The problem is... this attached function has `__lr_wrapper__ ` on it and it points to the LogRocket's function. So... how a non-LogRocket wrapper has been attached to document?

**Comment by gideonred** [comment]
This ticket has been moved to [FE-174](https://linear.app/replay/issue/FE-174/stuck-frame-progress-slider)

**Comment by Andarist** [comment]
@bvaughn I wonder, have you managed to fix this one perhaps?

**Comment by markerikson** [comment]
No, afraid we still haven't looked at it (largely due to lack of repro and other priorities).  I think Brian's just doing a cleanup sweep on GH issues atm.

**Comment by bvaughn** [comment]
@Andarist Nope. Just closing GitHub issues that (a) were opened by Replay employees and (b) have already been migrated to Linear.
