### ISSUE TITLE
Network Monitor -- Copy as CURL

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#8789]
We started it here, https://github.com/replayio/devtools/pull/7943

**Comment by faga295** [comment]
Can I work on this?

**Comment by jasonLaster** [comment]
@faga295 go for it

**Comment by faga295** [comment]
@vikneshwar I want to give you some advice: If you are interested in a task and see that someone is already preparing to do it, even if the draft PR has been submitted, you should at least let them know before you prepare to do it. Instead of silently submitting the PR and causing someone’s efforts to be wasted in the end.

**Comment by vikneshwar** [comment]
Hi @faga295 sorry that your effort on this PR is wasted, but I was totally unaware if this was being worked now I was aware that there is a draft PR already. I started to analyze on this way before, in fact you can see my message in the #development channel [here](https://discord.com/channels/779097926135054346/795692423513767956/1080546891453968505)

**Comment by bvaughn** [comment]
Thanks @faga295 and @vikneshwar for your contributions on this 🙇🏼‍♂️  and sorry for the miscommunications on our end.

This feature should be rolling out sometime today.
