### ISSUE TITLE
Add support for copying print statements from another recording

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#8790]
Now that we've got print statements being persisted to the backend, it would be neat if we could add an option to copy over print statements I've made in another recording.

Use case: I've got a couple recordings of the same example app (in this particular case an RTK bug repro), and I'm trying to compare behavior between the two recordings. I can look at the first tab, eyeball the print statements, and manually recreate them in the second tab, but it would be nice to have a menu item that lets me just grab all the print statements from the other recording and copy them over.

Questions to answer:

- How does the user pick the recording to start from? (would either need a list of recordings and a way to select one, or just paste in a recording ID)
- Would the imported print statements overwrite my existing ones, or merge into them?

Internal issue: FE-1276

**Comment by vikneshwar** [comment]
Hi, @markerikson I spend some time analyzing the codebase on how to implement this. To copy over the print statement, there are two options.

- one way to solve this is to get all the points for the recording in the frontend by calling the get API and add all the points to the other recording by calling the add API
- another option is to copy points from source recording to destination recording on the API side. So, when users clicks to copy and choose to paste on another recording, an API call is made with `sourceRecordingId` and `destinationRecordingId`, and the API takes care of copying the points. But I believe replay's API endpoint is close sourced, and there is no way for us contributors to gain access to code and help with this. But this option seems efficient and best way to handle it, instead of doing multiple API calls to get points and set points. 

Regarding the questions you have raised :

- I was thinking of having **Copy Print Statement** and **Paste Print Statement** menu items like **Rename**, **Delete**, **Share** in the **Your Library** page at `/team/me/recordings`
- To me merging the statements seems right way. 

Would like to know your opinion on this. Thanks

**Comment by bvaughn** [comment]
Closing this issue in GH. We'll continue to track via internal issue [FE-1276](https://linear.app/replay/issue/FE-1276)
