### ISSUE TITLE
Hoverboard flickers on load

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#8797]
Notice how when the panel changes the hoverboard is re-mounted

https://app.replay.io/recording/replay-devtools-flickers--6f3477e1-057a-4bd0-b6fb-2d003791070d?point=14603334915665569610340638706894161&time=5472

**Comment by anikdhabal** [comment]
can i work on this?

**Comment by jasonLaster** [comment]
@anikdhabal go for it

**Comment by PramodhTVK** [comment]
Can I start working on this?

**Comment by Shahbaz898414** [comment]
Can I work on this?

**Comment by jasonLaster** [comment]
@Shahbaz898414 @PramodhTVK go for it

**Comment by manavagr1108** [comment]
Hey @markerikson is it possible to provide more info on how to reproduce the error, cos I tried to few ways to reproduce the Flickers but I wasn't able to see the flickering. A replay video would be really helpful. Thanks!

**Comment by SalihuDickson** [comment]
Hey @markerikson, I've been taking a look at the issue, and it seems the flickering come from the loading screen unmounting and mounting again whenever the loading message needs to change. And the hoverboard svg doesn't always load quickly enough causing a stutter that's a bit drastic at times. My suggested solution is to alter the way the loading page works and just have it on the background by default with a function to change the message and return an empty fragment when the loading page is needed, that way svg doesn't need to keep reloading. 

This does seem like a bit of a drastic solution if the stuttering is manageable, in my opinion. Although I might be wrong about the issue or someone could use my diagnosis to come up with a better, easier to implement solution. But I wanted to check first to see if anyone has a better Idea or if this issue is not a big enough problem to alter how the loading screen works.

If anyone needs me to elaborate on what I'm talking about in any part of my comment, please let me know.

**Comment by jasonLaster** [comment]
@SalihuDickson that makes sense to me

**Comment by SalihuDickson** [comment]
@jasonLaster okay great! what do you think should be done though. Is the issue big enough to change how the landing page is loaded or is it manageable enough to just leave it, at alone least for now. Or are there any better solutions you might be thinking of.

Thanks for such a quick reply by the way.

**Comment by bvaughn** [comment]
Filed FE-1350
